package tcpmon

import (
	"fmt"
)

func boolToUint32(x bool) uint32 {
	if !x {
		return 0
	} else {
		return 1
	}
}

type TSDBMetricPrinter struct {}

func (tsdb TSDBMetricPrinter) PrintTcpMetric(m *TcpMetric, hostname string) {
	for _, socket := range m.GetSockets() {
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s State=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetState(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RecvQ=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRecvQ(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s SendQ=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSendQ(), m.GetTimestamp())

		for _, process := range socket.GetProcesses() {
			fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,ProcessName=%s,hostname=%s Pid=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), process.GetName(), hostname, process.GetPid(), m.GetTimestamp())
			fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,ProcessName=%s,hostname=%s Fd=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), process.GetName(), hostname, process.GetFd(), m.GetTimestamp())
		}

		for _, timer := range socket.GetTimers() {
			fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,TimerName=%s,hostname=%s ExpireTimeUs=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), timer.GetName(), hostname, timer.GetExpireTimeUs(), m.GetTimestamp())
			fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,TimerName=%s,hostname=%s Retrans=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), timer.GetName(), hostname, timer.GetRetrans(), m.GetTimestamp())
		}

		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RmemAlloc=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSkmem().GetRmemAlloc(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RcvBuf=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSkmem().GetRcvBuf(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s WmemAlloc=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSkmem().GetWmemAlloc(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s SndBuf=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSkmem().GetSndBuf(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s FwdAlloc=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSkmem().GetFwdAlloc(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s WmemQueued=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSkmem().GetWmemQueued(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s OptMem=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSkmem().GetOptMem(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s BackLog=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSkmem().GetBackLog(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s SockDrop=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSkmem().GetSockDrop(), m.GetTimestamp())

		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Ts=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, boolToUint32(socket.GetTs()), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Sack=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, boolToUint32(socket.GetSack()), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Cubic=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, boolToUint32(socket.GetCubic()), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s AppLimited=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, boolToUint32(socket.GetAppLimited()), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s PacingRate=%f %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetPacingRate(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s DeliveryRate=%f %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetDeliveryRate(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Send=%f %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSend(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s SndWscale=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSndWscale(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RcvWscale=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRcvWscale(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Rto=%f %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRto(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Rtt=%f %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRtt(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Rttvar=%f %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRttvar(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Minrtt=%f %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetMinrtt(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RcvRtt=%f %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRcvRtt(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RetransNow=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRetransNow(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RetransTotal=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRetransTotal(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Ato=%f %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetAto(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Mss=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetMss(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Pmtu=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetPmtu(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Rcvmss=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRcvmss(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Advmss=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetAdvmss(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Cwnd=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetCwnd(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s SndWnd=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSndWnd(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s BytesSent=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetBytesSent(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s BytesAcked=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetBytesAcked(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s BytesReceived=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetBytesReceived(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s SegsOut=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSegsOut(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s SegsIn=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSegsIn(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Lastsnd=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetLastsnd(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Lastrcv=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetLastrcv(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Lastack=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetLastack(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Delivered=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetDelivered(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s BusyMs=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetBusyMs(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RcvSpace=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRcvSpace(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RcvSsthresh=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRcvSsthresh(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s DataSegsOut=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetDataSegsOut(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s DataSegsIn=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetDataSegsIn(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s RwndLimited=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetRwndLimited(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s SndbufLimited=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, socket.GetSndbufLimited(), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Ecn=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, boolToUint32(socket.GetEcn()), m.GetTimestamp())
		fmt.Printf("tcp,LocalAddr=%s,PeerAddr=%s,hostname=%s Ecnseen=%d %d\n", socket.GetLocalAddr(), socket.GetPeerAddr(), hostname, boolToUint32(socket.GetEcnseen()), m.GetTimestamp())
	}
}

func (tsdb TSDBMetricPrinter) PrintNicMetric(m *NicMetric, hostname string) {
	for _, iface := range m.GetIfaces() {
		fmt.Printf("nic,name=%s,hostname=%s RxErrors=%d %d\n", iface.GetName(), hostname, iface.GetRxErrors(), m.GetTimestamp())
		fmt.Printf("nic,name=%s,hostname=%s RxDropped=%d %d\n", iface.GetName(), hostname, iface.GetRxDropped(), m.GetTimestamp())
		fmt.Printf("nic,name=%s,hostname=%s RxOverruns=%d %d\n", iface.GetName(), hostname, iface.GetRxOverruns(), m.GetTimestamp())
		fmt.Printf("nic,name=%s,hostname=%s RxFrame=%d %d\n", iface.GetName(), hostname, iface.GetRxFrame(), m.GetTimestamp())
		fmt.Printf("nic,name=%s,hostname=%s TxErrors=%d %d\n", iface.GetName(), hostname, iface.GetTxErrors(), m.GetTimestamp())
		fmt.Printf("nic,name=%s,hostname=%s TxDropped=%d %d\n", iface.GetName(), hostname, iface.GetTxDropped(), m.GetTimestamp())
		fmt.Printf("nic,name=%s,hostname=%s TxOverruns=%d %d\n", iface.GetName(), hostname, iface.GetTxOverruns(), m.GetTimestamp())
		fmt.Printf("nic,name=%s,hostname=%s TxCarrier=%d %d\n", iface.GetName(), hostname, iface.GetTxCarrier(), m.GetTimestamp())
		fmt.Printf("nic,name=%s,hostname=%s TxCollisions=%d %d\n", iface.GetName(), hostname, iface.GetTxCollisions(), m.GetTimestamp())
	}
}

func (tsdb TSDBMetricPrinter) PrintNetstatMetric(m *NetstatMetric, hostname string) {
	fmt.Printf("net,hostname=%s IpTotalPacketsReceived=%d %d\n", hostname, m.GetIpTotalPacketsReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpForwarded=%d %d\n", hostname, m.GetIpForwarded(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpIncomingPacketsDiscarded=%d %d\n", hostname, m.GetIpIncomingPacketsDiscarded(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpIncomingPacketsDelivered=%d %d\n", hostname, m.GetIpIncomingPacketsDelivered(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpRequestsSentOut=%d %d\n", hostname, m.GetIpRequestsSentOut(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpOutgoingPacketsDropped=%d %d\n", hostname, m.GetIpOutgoingPacketsDropped(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpDroppedBecauseOfMissingRoute=%d %d\n", hostname, m.GetIpDroppedBecauseOfMissingRoute(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpFragmentsDroppedAfterTimeout=%d %d\n", hostname, m.GetIpFragmentsDroppedAfterTimeout(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpReassembliesRequired=%d %d\n", hostname, m.GetIpReassembliesRequired(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpPacketsReassembledOk=%d %d\n", hostname, m.GetIpPacketsReassembledOk(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpPacketReassemblesFailed=%d %d\n", hostname, m.GetIpPacketReassemblesFailed(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpActiveConnectionsOpenings=%d %d\n", hostname, m.GetTcpActiveConnectionsOpenings(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpPassiveConnectionOpenings=%d %d\n", hostname, m.GetTcpPassiveConnectionOpenings(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpFailedConnectionAttempts=%d %d\n", hostname, m.GetTcpFailedConnectionAttempts(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpConnectionResetsReceived=%d %d\n", hostname, m.GetTcpConnectionResetsReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpConnectionsEstablished=%d %d\n", hostname, m.GetTcpConnectionsEstablished(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpSegmentsReceived=%d %d\n", hostname, m.GetTcpSegmentsReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpSegmentsSendOut=%d %d\n", hostname, m.GetTcpSegmentsSendOut(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpSegmentsRetransmitted=%d %d\n", hostname, m.GetTcpSegmentsRetransmitted(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpBadSegmentsReceived=%d %d\n", hostname, m.GetTcpBadSegmentsReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpResetsSent=%d %d\n", hostname, m.GetTcpResetsSent(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s UdpPacketsReceived=%d %d\n", hostname, m.GetUdpPacketsReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s UdpPacketsToUnknownPortReceived=%d %d\n", hostname, m.GetUdpPacketsToUnknownPortReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s UdpPacketReceiveErrors=%d %d\n", hostname, m.GetUdpPacketReceiveErrors(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s UdpPacketsSent=%d %d\n", hostname, m.GetUdpPacketsSent(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s UdpReceiveBufferErrors=%d %d\n", hostname, m.GetUdpReceiveBufferErrors(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s UdpSendBufferErrors=%d %d\n", hostname, m.GetUdpSendBufferErrors(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s UdpIgnoredMulti=%d %d\n", hostname, m.GetUdpIgnoredMulti(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextInvalidSynCookiesReceived=%d %d\n", hostname, m.GetTcpextInvalidSynCookiesReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextResetsReceivedForEmbryonicSynRecvSockets=%d %d\n", hostname, m.GetTcpextResetsReceivedForEmbryonicSynRecvSockets(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextIcmpPacketsDroppedBecauseTheyWereOutOfWindow=%d %d\n", hostname, m.GetTcpextIcmpPacketsDroppedBecauseTheyWereOutOfWindow(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextIcmpPacketsDroppedBecauseSocketWasLocked=%d %d\n", hostname, m.GetTcpextIcmpPacketsDroppedBecauseSocketWasLocked(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpSocketsFinishedTimeWaitInFastTimer=%d %d\n", hostname, m.GetTcpextTcpSocketsFinishedTimeWaitInFastTimer(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextPacketsRejectsInEstablishedConnectionsBecauseOfTimestamp=%d %d\n", hostname, m.GetTcpextPacketsRejectsInEstablishedConnectionsBecauseOfTimestamp(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextDelayedAcksSent=%d %d\n", hostname, m.GetTcpextDelayedAcksSent(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextDelayedAcksFurtherDelayedBecauseOfLockedSocket=%d %d\n", hostname, m.GetTcpextDelayedAcksFurtherDelayedBecauseOfLockedSocket(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextQuickAckModeWasActivatedTimes=%d %d\n", hostname, m.GetTcpextQuickAckModeWasActivatedTimes(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTimesTheListenQueueOfASocketOverflowed=%d %d\n", hostname, m.GetTcpextTimesTheListenQueueOfASocketOverflowed(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextSynsToListenSocketsDropped=%d %d\n", hostname, m.GetTcpextSynsToListenSocketsDropped(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextPacketHeadersPredicted=%d %d\n", hostname, m.GetTcpextPacketHeadersPredicted(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextAcknowledgmentsNotContainingDataPayloadReceived=%d %d\n", hostname, m.GetTcpextAcknowledgmentsNotContainingDataPayloadReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextPredictedAcknowledgments=%d %d\n", hostname, m.GetTcpextPredictedAcknowledgments(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTimesRecoveredFromPacketLossBySelectiveAcknowledgements=%d %d\n", hostname, m.GetTcpextTimesRecoveredFromPacketLossBySelectiveAcknowledgements(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextDetectedReorderingTimesUsingSack=%d %d\n", hostname, m.GetTcpextDetectedReorderingTimesUsingSack(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextCongestionWindowsFullyRecoveredWithoutSlowStart=%d %d\n", hostname, m.GetTcpextCongestionWindowsFullyRecoveredWithoutSlowStart(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextCongestionWindowsRecoveredWithoutSlowStartByDsack=%d %d\n", hostname, m.GetTcpextCongestionWindowsRecoveredWithoutSlowStartByDsack(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextCongestionWindowsRecoveredWithoutSlowStartAfterPartialAck=%d %d\n", hostname, m.GetTcpextCongestionWindowsRecoveredWithoutSlowStartAfterPartialAck(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpLostRetransmit=%d %d\n", hostname, m.GetTcpextTcpLostRetransmit(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTimeoutsAfterSackRecovery=%d %d\n", hostname, m.GetTcpextTimeoutsAfterSackRecovery(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTimeoutsInLossState=%d %d\n", hostname, m.GetTcpextTimeoutsInLossState(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextFastRetransmits=%d %d\n", hostname, m.GetTcpextFastRetransmits(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextRetransmitsInSlowStart=%d %d\n", hostname, m.GetTcpextRetransmitsInSlowStart(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextOtherTcpTimeouts=%d %d\n", hostname, m.GetTcpextOtherTcpTimeouts(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpLossProbes=%d %d\n", hostname, m.GetTcpextTcpLossProbes(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpLossProbeRecovery=%d %d\n", hostname, m.GetTcpextTcpLossProbeRecovery(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextSackRetransmitsFailed=%d %d\n", hostname, m.GetTcpextSackRetransmitsFailed(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpBacklogCoalesce=%d %d\n", hostname, m.GetTcpextTcpBacklogCoalesce(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextDsacksSentForOldPackets=%d %d\n", hostname, m.GetTcpextDsacksSentForOldPackets(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextDsacksSentForOutOfOrderPackets=%d %d\n", hostname, m.GetTcpextDsacksSentForOutOfOrderPackets(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextDsacksReceived=%d %d\n", hostname, m.GetTcpextDsacksReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextDsacksForOutOfOrderPacketsReceived=%d %d\n", hostname, m.GetTcpextDsacksForOutOfOrderPacketsReceived(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextConnectionsResetDueToUnexpectedData=%d %d\n", hostname, m.GetTcpextConnectionsResetDueToUnexpectedData(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextConnectionsResetDueToEarlyUserClose=%d %d\n", hostname, m.GetTcpextConnectionsResetDueToEarlyUserClose(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextConnectionsAbortedDueToTimeout=%d %d\n", hostname, m.GetTcpextConnectionsAbortedDueToTimeout(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpDsackIgnoredOld=%d %d\n", hostname, m.GetTcpextTcpDsackIgnoredOld(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpDsackIgnoredNoUndo=%d %d\n", hostname, m.GetTcpextTcpDsackIgnoredNoUndo(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpSpuriousRtos=%d %d\n", hostname, m.GetTcpextTcpSpuriousRtos(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpSackMerged=%d %d\n", hostname, m.GetTcpextTcpSackMerged(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpSackShiftFallback=%d %d\n", hostname, m.GetTcpextTcpSackShiftFallback(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextIpReversePathFilter=%d %d\n", hostname, m.GetTcpextIpReversePathFilter(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpRetransFail=%d %d\n", hostname, m.GetTcpextTcpRetransFail(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpRcvCoalesce=%d %d\n", hostname, m.GetTcpextTcpRcvCoalesce(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpOfoQueue=%d %d\n", hostname, m.GetTcpextTcpOfoQueue(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpOfoMerge=%d %d\n", hostname, m.GetTcpextTcpOfoMerge(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpChallengeAck=%d %d\n", hostname, m.GetTcpextTcpChallengeAck(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpSynChallenge=%d %d\n", hostname, m.GetTcpextTcpSynChallenge(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpFastOpenActiveFail=%d %d\n", hostname, m.GetTcpextTcpFastOpenActiveFail(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpFastOpenCookieReqd=%d %d\n", hostname, m.GetTcpextTcpFastOpenCookieReqd(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpFastOpenBlackhole=%d %d\n", hostname, m.GetTcpextTcpFastOpenBlackhole(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpSpuriousRtxHostQueues=%d %d\n", hostname, m.GetTcpextTcpSpuriousRtxHostQueues(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpAutoCorking=%d %d\n", hostname, m.GetTcpextTcpAutoCorking(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpSynRetrans=%d %d\n", hostname, m.GetTcpextTcpSynRetrans(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpOrigDataSent=%d %d\n", hostname, m.GetTcpextTcpOrigDataSent(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpHystartTrainDetect=%d %d\n", hostname, m.GetTcpextTcpHystartTrainDetect(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpHystartTrainCwnd=%d %d\n", hostname, m.GetTcpextTcpHystartTrainCwnd(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpHystartDelayDetect=%d %d\n", hostname, m.GetTcpextTcpHystartDelayDetect(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpHystartDelayCwnd=%d %d\n", hostname, m.GetTcpextTcpHystartDelayCwnd(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpAckSkippedSeq=%d %d\n", hostname, m.GetTcpextTcpAckSkippedSeq(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpAckSkippedChallenge=%d %d\n", hostname, m.GetTcpextTcpAckSkippedChallenge(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpKeepAlive=%d %d\n", hostname, m.GetTcpextTcpKeepAlive(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpDelivered=%d %d\n", hostname, m.GetTcpextTcpDelivered(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s TcpextTcpAckCompressed=%d %d\n", hostname, m.GetTcpextTcpAckCompressed(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpextInBcastPkts=%d %d\n", hostname, m.GetIpextInBcastPkts(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpextInOctets=%d %d\n", hostname, m.GetIpextInOctets(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpextOutOctets=%d %d\n", hostname, m.GetIpextOutOctets(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpextInBcastOctets=%d %d\n", hostname, m.GetIpextInBcastOctets(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpextInNoEctPkts=%d %d\n", hostname, m.GetIpextInNoEctPkts(), m.GetTimestamp())
	fmt.Printf("net,hostname=%s IpextInEct0Pkts=%d %d\n", hostname, m.GetIpextInEct0Pkts(), m.GetTimestamp())
}
